# Generated by Django 5.0.7 on 2024-09-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_billing_address'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
